language: go
go: "1.12"

install: true
deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io && make push-handler
  skip_cleanup: true
  on:
    branch: master
