apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge
spec:
  desiredState:
    interfaces:
    - name: br1
      description: ovs bridge with eth1 as a port
      type: ovs-bridge
      state: up
      bridge:
        options:
          stp: false
        port:
        - name: eth1
