apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: example-nodenetworkconfigurationpolicy
spec:
  priority: 99
  nodeSelector:
    kubernetes.io/hostname: node01
  desiredState:
    - name: eth1
      type: ethernet
      state: up
    - name: br1
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
          - name: eth1
            stp-hairpin-mode: false
            stp-path-cost: 100
            stp-priority: 32
