apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: example-nodenetworkconfigurationpolicy
spec:
  desiredState:
    interfaces:
    - name: eth1
      type: ethernet
      state: up
    - name: eth2
      type: ethernet
      state: up
    - name: br0
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
          - name: eth1
            stp-hairpin-mode: false
            stp-path-cost: 100
            stp-priority: 32
    - name: br1
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
          - name: eth2
            stp-hairpin-mode: false
            stp-path-cost: 100
            stp-priority: 32
