apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodenetworkconfigurationpolicies.nmstate.io
spec:
  group: nmstate.io
  names:
    kind: NodeNetworkConfigurationPolicy
    listKind: NodeNetworkConfigurationPolicyList
    plural: nodenetworkconfigurationpolicies
    singular: nodenetworkconfigurationpolicy
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            desiredState:
              description: The desired configuration of the policy
              type: object
            match:
              description: Criteria to apply this policy
              properties:
                nodes:
                  description: Node names to apply the policy
                  items:
                    type: string
                  type: array
              type: object
            priority:
              description: In case of multiple policies applying for the same node
                this priority define the order from low to high
              format: int64
              type: integer
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
