apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nmstate-handler
spec:
  selector:
    matchLabels:
      nmstate.io: nmstate-handler
  template:
    metadata:
      labels:
        nmstate.io: nmstate-handler
    spec:
      serviceAccount: kubernetes-nmstate
      containers:
        - name: nmstate-handler
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          volumeMounts:
          - name: dbus-socket
            mountPath: /run/dbus/system_bus_socket
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          securityContext:
            privileged: true
      volumes:
      - name: dbus-socket
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
