---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nmstate-handler
  namespace: nmstate
spec:
  selector:
    matchLabels:
      name: nmstate-handler
  template:
    metadata:
      labels:
        app: kubernetes-nmstate
        name: nmstate-handler
    spec:
      # Needed to force vlan filtering config with iproute commands until
      # future nmstate/NM is in place.
      # https://github.com/nmstate/nmstate/pull/440
      hostNetwork: true
      serviceAccountName: nmstate-handler
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nmstate-handler
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          command:
          - kubernetes-nmstate
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nmstate-handler"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_NETWORK_STATE_REFRESH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: nmstate-config
                  key: node_network_state_refresh_interval
          volumeMounts:
          - name: dbus-socket
            mountPath: /run/dbus/system_bus_socket
          securityContext:
            privileged: true
      volumes:
      - name: dbus-socket
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nmstate-config
  namespace: nmstate
data:
  node_network_state_refresh_interval: "5"