---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nmstate-handler
  namespace: nmstate
spec:
  selector:
    matchLabels:
      name: nmstate-handler
  template:
    metadata:
      labels:
        app: kubernetes-nmstate
        name: nmstate-handler
    spec:
      serviceAccountName: nmstate-handler
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nmstate-handler
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          command:
          - kubernetes-nmstate
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nmstate-handler"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: dbus-socket
            mountPath: /run/dbus/system_bus_socket
          securityContext:
            privileged: true
      volumes:
      - name: dbus-socket
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
